[platformio]
boards_dir = ../../paku_core/boards

[env:nrf-test]
platform = espressif32@6.5.0
board = lilygo-t-displays3
framework = arduino
upload_speed = 115200
monitor_port = /dev/cu.usbmodem1301
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = nrf24/RF24@^1.4.0
